services:
  # Backend API Service
  - type: web
    name: qr-code-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main

  # Frontend Static Site (Optional - can be served by backend)
  - type: web
    name: qr-code-frontend
    env: static
    plan: free
    buildCommand: echo "Frontend served by backend API"
    staticPublishPath: ./public
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
